spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: danone
    password: danone
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: WUFEU0pLREhKU0hETldFVUFOU0tKRE5BS0pTRE5BS1NOREFLU05ESktBU05ESktBU0Q=
      expiration: 86400000

  mailing:
    frontend:
      activation-url: http://localhost:4200/account-activate
